# CMake generated Testfile for 
# Source directory: /users/banspach/oss/third_party/sundials/sundials-3.1.0/examples/sunlinsol/band
# Build directory: /users/banspach/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/band
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_sunlinsol_band_10_2_3_0 "/soft/net/python" "/users/banspach/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunlinsol_band_10_2_3_0" "--executablename=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/band/test_sunlinsol_band" "--outputdir=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"10 2 3 0\"")
add_test(test_sunlinsol_band_300_7_4_0 "/soft/net/python" "/users/banspach/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunlinsol_band_300_7_4_0" "--executablename=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/band/test_sunlinsol_band" "--outputdir=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"300 7 4 0\"")
add_test(test_sunlinsol_band_1000_8_8_0 "/soft/net/python" "/users/banspach/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunlinsol_band_1000_8_8_0" "--executablename=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/band/test_sunlinsol_band" "--outputdir=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"1000 8 8 0\"")
add_test(test_sunlinsol_band_5000_3_100_0 "/soft/net/python" "/users/banspach/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunlinsol_band_5000_3_100_0" "--executablename=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/band/test_sunlinsol_band" "--outputdir=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"5000 3 100 0\"")
