install: true
language: cpp
addons:
  apt_packages:
    - gfortran
sudo: required
python: 
- '3.6'
before_install:
- echo Running before_install
- git clone --depth=50 --branch=master https://github.com/OpenMatrixLanguage/OpenMatrix.git OpenMatrixPublic
env:
  SH=bash
  OML_ROOT=$PWD/OpenMatrixPublic
  OML_THIRDPARTY=$PWD/third_party_linux
  LD_LIBRARY_PATH=$OML_THIRDPARTY/fftw/fftw-3.2.2/.libs:$LD_LIBRARY_PATH
  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OML_THIRDPARTY/lapack/lapack-3.7.1
  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OML_THIRDPARTY/ANTLR/libantlr3c-3.4/.libs
  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OML_THIRDPARTY/matio/matio-1.5.11/src/.libs
  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OML_THIRDPARTY/hdf5/hdf5-1.10.1/hdf5/lib
  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OML_THIRDPARTY/sundials/sundials-3.1.0-install/lib
  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OML_ROOT/src/bin/linux64
  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/bin:/usr/lib
  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu
  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib/x86_64-linux-gnu
  PATH=$PATH:$OML_ROOT/src/bin/linux64
  OML_PYTHONHOME=/usr
  OML_PYTHONVERSION=python3
  OML_PYTHON_NUMPYDIR=$OML_PYTHONHOME/lib/$OML_PYTHONVERSION/dist-packages/numpy/core/include/numpy/
before_script:
#- sudo add-apt-repository ppa:deadsnakes/ppa
#- sudo apt-get update
#- sudo apt-get install python3.6
#Fail error 6 curl -ubanspach:Hgrth67@ -O "http://dave-test.prog.altair.com:8081/artifactory/generic-local/dbagent-4.4.3.536.zip"
- "curl -u 'banspach:Hgrth67@' -O \""http://dave-test.prog.altair.com:8081/artifactory/generic-local/dbagent-4.4.3.536.zip\""
script:
#- ls -alF /usr/include/python3m
- ls -alF
- echo LIST /usr/bin/py*
- ls -alF /usr/bin/py*
- echo LIST /usr/lib/py*
- ls -alF /usr/lib/py*
- cd OpenMatrixPublic/src
- ls -alF
- make -f makefile.open
after_success:
after_success:
- chmod 777 $OML_ROOT/src/bin/linux64/omlconsole
- ls -alF $OML_ROOT/src/bin/linux64
- cd $OML_ROOT/Tests/RegressionTests && pwd
- perl ../regressOMLConsole.pl -travis
- cd $OML_ROOT/Tests
- source run_toolbox_tests.sh
- cd $OML_ROOT/Tests
- ls -alF ..
- ls -alF ../..
- ls -alF ../../..
- source ../../evaluate_test_results.sh
compiler: gcc
