# CMake generated Testfile for 
# Source directory: /users/banspach/oss/third_party/sundials/sundials-3.1.0/examples/sunlinsol/dense
# Build directory: /users/banspach/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/dense
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_sunlinsol_dense_10_0 "/soft/net/python" "/users/banspach/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunlinsol_dense_10_0" "--executablename=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/dense/test_sunlinsol_dense" "--outputdir=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"10 0\"")
add_test(test_sunlinsol_dense_100_0 "/soft/net/python" "/users/banspach/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunlinsol_dense_100_0" "--executablename=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/dense/test_sunlinsol_dense" "--outputdir=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"100 0\"")
add_test(test_sunlinsol_dense_500_0 "/soft/net/python" "/users/banspach/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunlinsol_dense_500_0" "--executablename=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/dense/test_sunlinsol_dense" "--outputdir=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"500 0\"")
add_test(test_sunlinsol_dense_1000_0 "/soft/net/python" "/users/banspach/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunlinsol_dense_1000_0" "--executablename=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/examples/sunlinsol/dense/test_sunlinsol_dense" "--outputdir=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"1000 0\"")
