# CMake generated Testfile for 
# Source directory: /users/banspach/oss/third_party/sundials/sundials-3.1.0/examples/sunmatrix/sparse
# Build directory: /users/banspach/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_sunmatrix_sparse_400_400_0_0 "/soft/net/python" "/users/banspach/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_400_400_0_0" "--executablename=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/test_sunmatrix_sparse" "--outputdir=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"400 400 0 0\"")
add_test(test_sunmatrix_sparse_450_450_1_0 "/soft/net/python" "/users/banspach/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_450_450_1_0" "--executablename=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/test_sunmatrix_sparse" "--outputdir=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"450 450 1 0\"")
add_test(test_sunmatrix_sparse_200_1000_0_0 "/soft/net/python" "/users/banspach/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_200_1000_0_0" "--executablename=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/test_sunmatrix_sparse" "--outputdir=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"200 1000 0 0\"")
add_test(test_sunmatrix_sparse_6000_350_0_0 "/soft/net/python" "/users/banspach/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_6000_350_0_0" "--executablename=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/test_sunmatrix_sparse" "--outputdir=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"6000 350 0 0\"")
add_test(test_sunmatrix_sparse_500_5000_1_0 "/soft/net/python" "/users/banspach/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_500_5000_1_0" "--executablename=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/test_sunmatrix_sparse" "--outputdir=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"500 5000 1 0\"")
add_test(test_sunmatrix_sparse_4000_800_1_0 "/soft/net/python" "/users/banspach/oss/third_party/sundials/sundials-3.1.0/test/testRunner" "--verbose" "--testname=test_sunmatrix_sparse_4000_800_1_0" "--executablename=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/examples/sunmatrix/sparse/test_sunmatrix_sparse" "--outputdir=/users/banspach/oss/third_party/sundials/sundials-3.1.0-build/Testing/output" "--nodiff" "--runargs=\"4000 800 1 0\"")
